version: "3.8"

services:
  postgres:
    image: postgres:13
    container_name: "${POSTGRES_USER}-db"
    ports:
      - "${POSTGRES_LOCAL_PORT}:5432"
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - db_data:/var/lib/postgresql/data
    # command: ["postgres", "-c", "log_statement=all"] # to log SQL

  mailhog:
    image: mailhog/mailhog:latest
    container_name: "mailhog"
    ports:
      - "1025:${MAIL_PORT}"
      - "8025:8025"
    restart: always

volumes:
  db_data:
